### PR TITLE
RBI input streaming + multiple keys + UI fixups

### PR DESCRIPTION
**Pull request by LuKePicci**
- Single RBI processing stream
- Support multiple (osik, osck) couples per board
- UI refinements and fixes for small screens
- Add GBNT-2 keys

Also addresses #7 and #14

### CODE REVIEW

**Comment by Ansuel** [comment]
Thx a lot for the work! Do you have other cleanup?

**Comment by LuKePicci** [comment]
I think that's all for now, signcheck and batch decrypt might come in future.

That other old PR about memory warnings is superseeded as well.

**Comment by FrancYescO** [comment]
add version bump ;)

**Comment by LuKePicci** [comment]
Done

**Pull request merged**
