### PR TITLE
Add VANT-R board

### PR DESCRIPTION
**Pull request by LuKePicci**

### CODE REVIEW

**Comment by Ansuel** [comment]
ma abbiamo rbi di questi firmware? hai per caso anche la chiave per verificare la firma?

**Comment by LuKePicci** [comment]
Sure, I've got RBIs for 16.2 and 17.2 at least, I have to recover that one for 15.x, will do as soon as I get access to Telia network.

I have the OSIK too - for this board and a lot of others. OSIK keys are too long, to stay inside board.java, I'd like to patch this app to get keys (both OSCK and OSIK) automatically from github once the RBI is given - or the board is selected, but I have some doubts on this, it could be easier to just get the keys from github and get rid of maintaining a known board list in the app itself. This is in my long term agenda so, don't expect anything anytime soon.

**Comment by Ansuel** [comment]
@LuKePicci mh... could be usefull but keep IMHO keep this tool "local" is better

**Comment by LuKePicci** [comment]
You're right, that's what I still need to think about, I would like to keep it working in both ways, and I need to sort out how to design such a thing. I will probably let it download the keys folder as ZIP from a predefined github URL. The URL/filepath of this ZIP would be editable by user in case it changes or the zip is offline as It would accept local filepaths as well. A "current" keys ZIP can be made available inside the jar resources.

**Comment by Ansuel** [comment]
yes this would be the perfect solution...
key downloaded but still ship some type of fallback in the jar

**Pull request merged**
