### PR TITLE
Fixed pom.xml

### PR DESCRIPTION
**Pull request by smx-smx**
I couldn't build the project with the current pom.xml out of the box (using `mvn`)
I also had troubles building on macOS

Added missing dependencies
- org.openjfx:javafx
- org.openjfx:javafx-controls
- javax.xml.bind:jaxb-api

Added javafx-maven-plugin
Added maven-assembly-plugin for build with dependencies included

### CODE REVIEW

**Comment by Ansuel** [comment]
@smx-smx does the application actually work with this pom.xml?

**Comment by smx-smx** [comment]
@Ansuel i'm using `mvn package` as a mean of verification.
If you run `mvn package` with your original pom.xml, it will fail to build

With my updated pom.xml, the application builds and runs fine on both Windows and MacOS.
Yes i had to update to Java 11, but that might have to do with the version of JavaFX i picked from the Maven repository

The `maven-assembly-plugin` is used to package JavaFX in a standalone jar file

**Comment by smx-smx** [comment]
`mvn clean assembly:assembly`
`java -jar target/Decrypt_RBI_Firmware_Utility-jar-with-dependencies.jar`
proof

**Comment by Ansuel** [comment]
Can you tell me the java version installed on the system

Il Mar 29 Ott 2019, 21:21 smx <notifications@github.com> ha scritto:

**Comment by smx-smx** [comment]
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by FrancYescO** [comment]
is decrypt ok on your system? (https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/issues/6)

**Comment by smx-smx** [comment]
I decrypted a DGA4131 firmware, all good

**Comment by smx-smx** [comment]
Any update on this? the program works perfectly with the pom.xml i attached (tested Windows and macOS succesfully - runs and decrypts properly).
The only issue i saw in this repository was the circleci configuration (wrong Java version), which could be fixed (in either pom.xml, by changing the JavaFX version, or by updating the java version in circleci)

**Pull request merged**
